ROLE_LIST = [
    "Software Engineering Intern",
    "Backend Intern",
    "Frontend Intern",
    "Full Stack Intern",
    "Web Development Intern",
    "Mobile App Developer Intern",
    "DevOps Intern",
    "Site Reliability Intern",
    "Cloud Engineering Intern",
    "Machine Learning Intern",
    "Data Engineering Intern",
    "AI Intern",
    "Embedded Systems Intern",
    "Game Developer Intern",
    "Cybersecurity Intern",
    "Blockchain Intern",
    "Computer Vision Intern",
    "Data Analyst Intern",
    "Data Science Intern",
    "Business Intelligence Intern",
    "Quantitative Analyst Intern",
    "Research Analyst Intern",
    "Statistical Modeling Intern",
    "Research Intern",
    "Applied Scientist Intern",
    "NLP Research Intern",
    "AI Research Intern",
    "Computer Science Research Intern",
    "UX Research Intern",
    "Product Management Intern",
    "Technical Program Manager Intern",
    "Product Designer Intern",
    "UX/UI Design Intern",
    "Human-Computer Interaction Intern",
    "Product Analyst Intern",
    "IT Intern",
    "QA Intern",
    "Test Engineering Intern",
    "Technical Support Intern",
    "Solutions Engineering Intern",
    "Software QA Intern",
    "Automation Intern",
    "System Admin Intern"
]