services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    env_file: .env
    develop:
      watch:
        - path: ./app
          action: sync
          target: /app
        - path: ./tests
          action: sync
          target: /tests
        - path: ./alembic
          action: sync
          target: /alembic
        - path: .
          action: sync+restart
          target: requirements.txt
