services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
      localstack:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/postgres
      - SYNC_DATABASE_URL=postgresql://postgres:password@db:5432/postgres
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - R2_BUCKET_URL=http://localstack:4566/my-bucket
      - R2_BUCKET_NAME=my-bucket
      - R2_REGION=us-east-1
    command: /app/start.sh
    develop:
      watch:
        - path: ./app
          action: sync
          target: /app
        - path: ./tests
          action: sync
          target: /tests
        - path: ./alembic
          action: sync
          target: /alembic
        - path: .
          action: sync+restart
          target: requirements.txt

  redis:
    image: redis:8.0.2
    container_name: redis
    ports:
    - 6379:6379
    volumes: 
     - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    restart: unless-stopped

  db:
    image: postgres:17.5
    container_name: db
    ports:
    - 5432:5432
    volumes:
    - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=password

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=0
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal s3 ls
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - r2-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init_bucket.sh:/etc/localstack/init/ready.d/init_bucket.sh

volumes:
  redis-data:
  db-data:
  r2-data:

