"""add upload_resume column in user_skills_and_preferences

Revision ID: 0625051779ba
Revises: 
Create Date: 2025-06-10 17:07:57.417923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0625051779ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['id'])
    op.add_column('user_skills_and_preferences', sa.Column('has_uploaded', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_skills_and_preferences', 'has_uploaded')
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
