"""Move has_uploaded column to user

Revision ID: e5eef6c4ff2e
Revises: 0625051779ba
Create Date: 2025-06-10 21:26:01.606328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5eef6c4ff2e'
down_revision: Union[str, None] = '0625051779ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_uploaded', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_column('user_skills_and_preferences', 'has_uploaded')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_skills_and_preferences', sa.Column('has_uploaded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('user', 'has_uploaded')
    # ### end Alembic commands ###
