name: CI on dev

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout dev branch
      uses: actions/checkout@v4
      with:
        ref: dev

    - name: Log in to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and tag image
      run: |
        IMAGE=ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/intern-hunters-backend:latest
        docker build -t $IMAGE .

    - name: Run linter in container
      run: |
        IMAGE=ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/intern-hunters-backend:latest
        docker run --rm \
          -e JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
          -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
          -e REFRESH_TOKEN_SECRET_KEY="${{ secrets.REFRESH_TOKEN_SECRET_KEY }}" \
          -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
          -e SYNC_DATABASE_URL="${{ secrets.SYNC_DATABASE_URL }}" \
          -e R2_ACCESS_KEY_ID="${{ secrets.R2_ACCESS_KEY_ID }}" \
          -e R2_SECRET_ACCESS_KEY="${{ secrets.R2_SECRET_ACCESS_KEY }}" \
          -e R2_BUCKET_NAME="${{ secrets.R2_BUCKET_NAME }}" \
          -e R2_BUCKET_URL="${{ secrets.R2_BUCKET_URL }}" \
          -e R2_REGION="${{ secrets.R2_REGION }}" \
          -e REDIS_HOST="${{ secrets.REDIS_HOST }}" \
          -e REDIS_PORT="${{ secrets.REDIS_PORT }}" \
          $IMAGE flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests in container
      run: |
        IMAGE=ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/intern-hunters-backend:latest
        docker run --rm \
          -e JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
          -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
          -e REFRESH_TOKEN_SECRET_KEY="${{ secrets.REFRESH_TOKEN_SECRET_KEY }}" \
          -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
          -e SYNC_DATABASE_URL="${{ secrets.SYNC_DATABASE_URL }}" \
          -e R2_ACCESS_KEY_ID="${{ secrets.R2_ACCESS_KEY_ID }}" \
          -e R2_SECRET_ACCESS_KEY="${{ secrets.R2_SECRET_ACCESS_KEY }}" \
          -e R2_BUCKET_NAME="${{ secrets.R2_BUCKET_NAME }}" \
          -e R2_BUCKET_URL="${{ secrets.R2_BUCKET_URL }}" \
          -e R2_REGION="${{ secrets.R2_REGION }}" \
          -e REDIS_HOST="${{ secrets.REDIS_HOST }}" \
          -e REDIS_PORT="${{ secrets.REDIS_PORT }}" \
          $IMAGE pytest

    - name: Push image
      run: |
        IMAGE=ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/intern-hunters-backend:latest
        docker push $IMAGE
