name: CD on Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::368339042148:role/github_deploy
        aws-region: ap-southeast-1

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Pull previous image for cache
      env: 
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: orbital/backend
      run: |
        docker pull $REGISTRY/$REPOSITORY:latest || true

    - name: Build, tag, push docker image to AWS ECR
      env: 
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: orbital/backend
      run: |
        docker build \
        --cache-from=$REGISTRY/$REPOSITORY:latest \
        -t $REGISTRY/$REPOSITORY:latest .
        docker push $REGISTRY/$REPOSITORY:latest

    - name: Re-deploy ECS service
      run: |
        aws ecs update-service \
        --cluster arn:aws:ecs:ap-southeast-1:368339042148:cluster/orbital_ii \
        --service arn:aws:ecs:ap-southeast-1:368339042148:service/orbital_ii/orbital-backend-service-mi60tlsm \
        --force-new-deployment
