name: CD on Main

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Pulls image from GHCR
      run: docker pull ghcr.io/${{ github.repository_owner }}/intern-hunters-backend:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::368339042148:role/github_deploy
        aws-region: ap-southeast-1

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Tag and push docker image to AWS ECR
      env: 
        AWS_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        AWS_REPOSITORY: orbital/backend
      run: |
        docker tag ghcr.io/${{ github.repository_owner }}/intern-hunters-backend:latest \
        $AWS_REGISTRY/$AWS_REPOSITORY:latest
        docker push $AWS_REGISTRY/$AWS_REPOSITORY:latest

    - name: Re-deploy ECS service
      run: |
        aws ecs update-service \
        --cluster arn:aws:ecs:ap-southeast-1:368339042148:cluster/orbital-ii \
        --service arn:aws:ecs:ap-southeast-1:368339042148:service/orbital-ii/orbital-backend-service-omkwionq \
        --force-new-deployment
