# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI on Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      REFRESH_TOKEN_SECRET_KEY: ${{ secrets.REFRESH_TOKEN_SECRET_KEY }}
      TEST_RESUME: ${{ secrets.TEST_RESUME }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      SYNC_DATABASE_URL: ${{ secrets.SYNC_DATABASE_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
      R2_BUCKET_URL: ${{ secrets.R2_BUCKET_URL }}
      R2_REGION: ${{ secrets.R2_REGION }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Download test resume
      run: |
        curl -L "$TEST_RESUME" -o ./tests/test_resume.pdf
        - name: Download LaTeX packages
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends \
          build-essential \
          ca-certificates \
          texlive-xetex \
          texlive-fonts-recommended \
          texlive-fonts-extra \
          texlive-latex-recommended \
          texlive-latex-extra \
          lmodern
    - name: Lint with flake8
      run: |
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest